### ISSUE TITLE
The reconstructed result is flatten 

### ISSUE THREAD

**Issue by xmlyqing00** [jsnln/ParametricGaussRecon#3]
Hi,

I compiled the project in windows and everything looks good. Running the program is also success. But the resulted meshes are flattern. Do you know why?

Thanks

![image](https://github.com/jsnln/ParametricGaussRecon/assets/8945602/55e8655a-ded0-4949-bed3-c1e057f5a9da)

Logs:

![image](https://github.com/jsnln/ParametricGaussRecon/assets/8945602/030e2e95-a43d-48ba-a91e-105b04ac3e75)
![image](https://github.com/jsnln/ParametricGaussRecon/assets/8945602/4b071a84-ee7c-4401-91bf-60b36f062112)

**Comment by jsnln** [comment]
Hi, I am not sure at the moment since I haven't tried it on windows. I am suspecting some IO incompatibility between windows and linux. Can you send me all the intermediate files for this example? Also, did you modify any build settings when compiling it on windows?

**Comment by xmlyqing00** [comment]
No, I didn't modify the build for window compilation, I used the vcpkg to link the required lib.
I used WSL to compile it again the results are promising. I believe it is just some environment issue. I attached the files that are generated from the Windows version. The inputs are your sample meshes.

I still need the Windows version to work because my other modules are compatible with Windows only.

Thanks for your help! 

[Armadillo_40000.zip](https://github.com/jsnln/ParametricGaussRecon/files/15085466/Armadillo_40000.zip)

**Comment by jsnln** [comment]
Hi, I guess the problem is with PGRLoadQuery, since every intermediate files looks OK except the final reconstruction. Though I am not sure exactly what went wrong, I was able to compile a new PGRLoadQuery on Windows and it works as expected. Try the attached exe [(pgr_exe.zip)](https://github.com/jsnln/ParametricGaussRecon/files/15125813/pgr_exe.zip) with the following command:

`apps\Release\PGRLoadQuery.exe -i Armadillo_40000\samples\Armadillo_40000.xyz -o a.ply --grid_val Armadillo_40000\solve\Armadillo_40000_k_7_min_0.0015_max_0.015_alpha_1.05_depth_min_1_depth_max_1_eval_grid.npy --grid_width Armadillo_40000\solve\Armadillo_40000_k_7_min_0.0015_max_0.015_alpha_1.05_depth_min_1_depth_max_1_grid_width.npy --isov -0.49866751 -d 10`

If it matters, to compile successfully with vs 2022 and vcpkg, I changed the `unistd.h` to `io.h` in `zconf.h` (a zlib include file located in `C:\Program Files (x86)\zlib\include`).

**Comment by xmlyqing00** [comment]
Thanks for your reply!!!
I will try it.
